/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

export const Colors = {
  light: {
    text: '#1d1d1f',
    background: '#f8f9fa',
    tint: '#2e7d32',
    icon: '#1d1d1f',
    tabIconDefault: '#8e8e93',
    tabIconSelected: '#2e7d32',
    primary: '#2e7d32',
    primaryForeground: '#fff',
    secondary: '#8d6e63',
    secondaryForeground: '#fff',
    muted: '#f2f2f7',
    mutedForeground: '#8e8e93',
    accent: '#e8f5e8',
    accentForeground: '#2e7d32',
    destructive: '#ff3b30',
    destructiveForeground: '#fff',
    border: '#0000001f',
    input: 'transparent',
    inputBackground: '#f2f2f7',
    switchBackground: '#e9ecef',
    ring: '#2e7d32',
    card: '#fff',
    cardForeground: '#1d1d1f',
    popover: '#fff',
    popoverForeground: '#1d1d1f',
    shadowColor: '#000',
  },
  dark: {
    text: '#fff',
    background: '#000',
    tint: '#30d158',
    icon: '#fff',
    tabIconDefault: '#8e8e93',
    tabIconSelected: '#30d158',
    primary: '#30d158',
    primaryForeground: '#000',
    secondary: '#a0845c',
    secondaryForeground: '#fff',
    muted: '#2c2c2e',
    mutedForeground: '#8e8e93',
    accent: '#1a3d1c',
    accentForeground: '#30d158',
    destructive: '#ff453a',
    destructiveForeground: '#fff',
    border: '#ffffff1f',
    input: '#2c2c2e',
    inputBackground: '#2c2c2e', // Assuming same as input
    switchBackground: '#2c2c2e', // Assuming same as input
    ring: '#30d158',
    card: '#1c1c1e',
    cardForeground: '#fff',
    popover: '#1c1c1e',
    popoverForeground: '#fff',
    shadowColor: '#fff',
  },
};
